### ISSUE TITLE
dcfetch doesn't work with subdirs

### ISSUE THREAD

**Issue by camante** [ciresdem/geomods#3]
@matth-love got error "Failed to change directory." when downloading lidar with subdirs. I think this was a previous issue that you had fixed....

ex. 
https://coast.noaa.gov/htdata/lidar1_z/geoid12b/data/4800/

dcfetch.py -R ga_sc_tiles_buff_v1.shp --filter "ID = 4800"

**Comment by camante** [comment]
@matth-love actually, might be just unique issue to that data set due to a permissions issue 

dcfetch.py -R ga_sc_tiles_buff_v1.shp --filter "ID = 4800" -x

Shows two data sets:

4800 (lidar): 2014 NOAA Post Hurricane Sandy Topobathymetric LiDAR Mapping for Shoreline Mapping (2014) - ftp://ftp.coast.noaa.gov/pub/DigitalCoast/lidar1_z/geoid12b/data/4800/
4800 (lidar): 2014 NOAA Post Hurricane Sandy Topobathymetric LiDAR Mapping for Shoreline Mapping (2014) - ftp://ftp.coast.noaa.gov/pub/DigitalCoast/lidar2_z/geoid12b/data/4800/

The lidar2_z is not allowed. Maybe that is why I get the error message: 
ftplib.error_perm: 550 Failed to change directory.

**Comment by matth-love** [comment]
Looks like this is a bug introduced by my recent update due to digital coast updating their ftp site and metadata. I tried to fudge it until next week when they can fix the raster datasets; but that seems to have duplicated some entries which were moved.
the duplication is fixed and the lidar datasets are updated in the latest update, but rasters won't be included until next week...

**Comment by matth-love** [comment]
FTP for rasters has been updated and all should work again as normal.
